application:
  kafka:
    topic_prod: "new_orders"
    topic_cons: "payed_orders"


spring:
  kafka:
    producer:
      bootstrap-servers: "127.0.0.1:9092"
      client-id: "orders-producer"
      acks: 1
    consumer:
      bootstrap-servers: "127.0.0.1:9092"

server:
  port: 8000
